### ISSUE TITLE
Question about Serial scheduler and parallel scheduler

### ISSUE THREAD

**Issue by zoechoutw** [ARM-software/mango#97]
Thank you for the amazing work! I have questions about the definition. 
1. I wonder if @Serial scheduler is to execute the original Bayesian optimization algorithm without parallelization? 
2. Could I assume that if I don't specify the scheduler, Serial scheduler is used by default? 
3. To perform Bayesian optimization in parallel, what are the definition of n_jobs and batch_size for?  What happens if the numbers are different? ex. n_jobs=m and batch_size=n. Does it run m runs or n runs simultaneously?

Thank you very much!

**Comment by tihom** [comment]
@zoechoutw thanks for the questions. Here are the answers:
1. I wonder if @Serial scheduler is to execute the original Bayesian optimization algorithm without parallelization? 
Yes, it runs with `batch_size=1`

2. Could I assume that if I don't specify the scheduler, Serial scheduler is used by default? 
No. In that case, the `batch_param=1` by default but the user has to modify the objective function to accept a list of params and return a list of results. See the notebook [here](https://github.com/ARM-software/mango/blob/main/examples/Convex_Function_Example.ipynb) for a working example.

3. To perform Bayesian optimization in parallel, what are the definition of n_jobs and batch_size for?  What happens if the numbers are different? ex. n_jobs=m and batch_size=n. Does it run m runs or n runs simultaneously?
the `batch_size` is overwritten with the value provided for `n_jobs`  when `@scheduler.parallel(n_jobs=xx)` is used.

**Comment by zoechoutw** [comment]
Thank you for your clear explaination!
